# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 20201029 branch
on:
  push:
    branches: [ 20201029 ]
  pull_request:
    branches: [ 20201029 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
          - name: LGTM Reaction
  # You may pin to the exact commit or the version.
  # uses: micnncim/action-lgtm-reaction@4b0c3ab3be53fcab2e4597abe455ec30158554bb
  uses: micnncim/action-lgtm-reaction@v0.6.0
  with:
    # Trigger comment on issue to send reaction
    trigger: # optional, default is ["^lgtm$", "^[gG]ood [jJ]ob!?$"]
    # Whether the original comment is overridden
    overide: # optional, default is false
    # Source providing LGTM image
    source: # optional, default is lgtmapp
